// Code generated by "stringer -type=Type -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LeftParen-0]
	_ = x[RightParen-1]
	_ = x[LeftBrace-2]
	_ = x[RightBrace-3]
	_ = x[Comma-4]
	_ = x[Dot-5]
	_ = x[Minus-6]
	_ = x[Plus-7]
	_ = x[Semicolon-8]
	_ = x[Slash-9]
	_ = x[Star-10]
	_ = x[QuestionMark-11]
	_ = x[Colon-12]
	_ = x[Bang-13]
	_ = x[BangEqual-14]
	_ = x[Equal-15]
	_ = x[EqualEqual-16]
	_ = x[Greater-17]
	_ = x[GreaterEqual-18]
	_ = x[Less-19]
	_ = x[LessEqual-20]
	_ = x[Identifier-21]
	_ = x[String-22]
	_ = x[Number-23]
	_ = x[keywordStart-24]
	_ = x[And-25]
	_ = x[Class-26]
	_ = x[Else-27]
	_ = x[False-28]
	_ = x[Fun-29]
	_ = x[For-30]
	_ = x[If-31]
	_ = x[Nil-32]
	_ = x[Or-33]
	_ = x[Print-34]
	_ = x[Return-35]
	_ = x[Super-36]
	_ = x[This-37]
	_ = x[True-38]
	_ = x[Var-39]
	_ = x[While-40]
	_ = x[keywordEnd-41]
	_ = x[EOF-42]
	_ = x[numTokens-43]
}

const _Type_name = "LeftParenRightParenLeftBraceRightBraceCommaDotMinusPlusSemicolonSlashStarQuestionMarkColonBangBangEqualEqualEqualEqualGreaterGreaterEqualLessLessEqualIdentifierStringNumberkeywordStartandclasselsefalsefunforifnilorprintreturnsuperthistruevarwhilekeywordEndEOFnumTokens"

var _Type_index = [...]uint16{0, 9, 19, 28, 38, 43, 46, 51, 55, 64, 69, 73, 85, 90, 94, 103, 108, 118, 125, 137, 141, 150, 160, 166, 172, 184, 187, 192, 196, 201, 204, 207, 209, 212, 214, 219, 225, 230, 234, 238, 241, 246, 256, 259, 268}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
