// Code generated by "stringer -type=Type -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LeftParen-0]
	_ = x[RightParen-1]
	_ = x[LeftBrace-2]
	_ = x[RightBrace-3]
	_ = x[Comma-4]
	_ = x[Dot-5]
	_ = x[Minus-6]
	_ = x[Plus-7]
	_ = x[Semicolon-8]
	_ = x[Slash-9]
	_ = x[Star-10]
	_ = x[Bang-11]
	_ = x[BangEqual-12]
	_ = x[Equal-13]
	_ = x[EqualEqual-14]
	_ = x[Greater-15]
	_ = x[GreaterEqual-16]
	_ = x[Less-17]
	_ = x[LessEqual-18]
	_ = x[Identifier-19]
	_ = x[String-20]
	_ = x[Number-21]
	_ = x[keywordStart-22]
	_ = x[And-23]
	_ = x[Class-24]
	_ = x[Else-25]
	_ = x[False-26]
	_ = x[Fun-27]
	_ = x[For-28]
	_ = x[If-29]
	_ = x[Nil-30]
	_ = x[Or-31]
	_ = x[Print-32]
	_ = x[Return-33]
	_ = x[Super-34]
	_ = x[This-35]
	_ = x[True-36]
	_ = x[Var-37]
	_ = x[While-38]
	_ = x[keywordEnd-39]
	_ = x[EOF-40]
	_ = x[numTokens-41]
}

const _Type_name = "LeftParenRightParenLeftBraceRightBraceCommaDotMinusPlusSemicolonSlashStarBangBangEqualEqualEqualEqualGreaterGreaterEqualLessLessEqualIdentifierStringNumberkeywordStartandclasselsefalsefunforifnilorprintreturnsuperthistruevarwhilekeywordEndEOFnumTokens"

var _Type_index = [...]uint8{0, 9, 19, 28, 38, 43, 46, 51, 55, 64, 69, 73, 77, 86, 91, 101, 108, 120, 124, 133, 143, 149, 155, 167, 170, 175, 179, 184, 187, 190, 192, 195, 197, 202, 208, 213, 217, 221, 224, 229, 239, 242, 251}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
