name: Go

on:
  pull_request:
    branches: 
      - main
    paths:
      - .github/workflows/go.yml
      - go.mod
      - go.sum
      - glox/**.go

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: false

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.55.2
        working-directory: glox
        skip-cache: true
  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: false

    - name: test
      run: go test -v ./... -race -count=10
      working-directory: glox
